
name:                chatter
version:             0.9.1.0
synopsis:            A library of simple NLP algorithms.
# description:         chatter is a collection of simple Natural Language
#                      Processing algorithms.
#                      .
#                      Chatter supports:
#                      .
#                      * Part of speech tagging with Averaged
#                        Perceptrons. Based on the Python implementation
#                        by Matthew Honnibal:
#                        (<http://honnibal.wordpress.com/2013/09/11/a-good-part-of-speechpos-tagger-in-about-200-lines-of-python/>) See 'NLP.POS' for the details of part-of-speech tagging with chatter.
#                      .
#                      * Phrasal Chunking (also with an Averaged Perceptron) to identify arbitrary chunks based on training data.
#                      .
#                      * Document similarity; A cosine-based similarity measure, and TF-IDF calculations,
#                        are available in the 'NLP.Similarity.VectorSim' module.
#                      .
#                      * Information Extraction patterns via (<https://wiki.haskell.org/Parsec>) Parsec
#                      .
#                      Chatter comes with models for POS tagging and
#                      Phrasal Chunking that have been trained on the
#                      Brown corpus (POS only) and the Conll2000 corpus
#                      (POS and Chunking)
homepage:            http://github.com/creswick/chatter
bug-reports:         http://github.com/creswick/chatter/issues
category:            Natural language processing
license-file:        LICENSE
author:              Rogan Creswick
maintainer:          creswick@gmail.com
extra-source-files:  changelog.md

data-files:          
  - data/models/README
  - data/models/brown.pos.model.gz
  - data/models/conll2000.pos.model.gz
  - data/models/conll2000.chunk.model.gz
  - data/models/wikiner.ner.model.gz

dependencies:
 - base           >= 4.6 && <= 6
 - text           >= 0.11.3.0
 - containers     >= 0.5.0.0
 - random-shuffle >= 0.0.4
 - MonadRandom    >= 0.1.2
 - cereal         >= 0.4.0.1 && <= 0.5.9.0
 - cereal-text    >= 0.1 && < 0.2
 - fullstop       >= 0.1.3.1
 - bytestring     >= 0.10.0.0
 - directory
 - mbox           >= 0.3
 - zlib           >= 0.5.4.1
 - filepath       >= 1.3.0.1
 - deepseq
 - tokenize       >= 0.2.0
 - parsec         >= 3.1.5
 - transformers
 - regex-tdfa     >= 1.2.0
 - array
 - QuickCheck
 - quickcheck-instances
 - unordered-containers
 - hashable


ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -fprof-auto
- -fprof-cafs



library:
  source-dirs: src
  other-modules: Paths_chatter
  exposed-modules:
    - NLP.POS
    - NLP.POS.AvgPerceptronTagger
    - NLP.POS.LiteralTagger
    - NLP.POS.UnambiguousTagger
    - NLP.Chunk
    - NLP.Chunk.AvgPerceptronChunker
    - NLP.ML.AvgPerceptron
    - NLP.Types
    - NLP.Types.General
    - NLP.Types.IOB
    - NLP.Types.Tags
    - NLP.Types.Tree
    - NLP.Tokenize.Chatter
    - NLP.Corpora.Parsing
    - NLP.Corpora.Email
    - NLP.Corpora.Brown
    - NLP.Corpora.Conll
    - NLP.Corpora.WikiNer
    - NLP.Similarity.VectorSim
    - NLP.Extraction.Parsec
    - NLP.Extraction.Examples.ParsecExamples
    - Data.DefaultMap

executables:
  tagPOS:
    main: Tagger.hs
    source-dirs: appsrc
    ghc-options: -main-is Tagger
    dependencies:
      - chatter  

  trainPOS:
    main: POSTrainer.hs
    source-dirs: appsrc
    ghc-options: -main-is POSTrainer
    dependencies:
      - chatter

  trainChunker:
    main: ChunkTrainer.hs
    source-dirs: appsrc
    ghc-options: -main-is ChunkTrainer
    dependencies:
      - chatter

  trainNER:
    main: NERTrainer.hs
    source-dirs: appsrc
    ghc-options: -main-is NERTrainer
    dependencies:
      - chatter

  eval:
    main: Evaluate.hs
    source-dirs: appsrc
    ghc-options: -main-is Evaluate
    dependencies:
      - chatter

# tests:
#   tests:
#     main: Main.hs
#     source-dirs: tests/src
#     other-modules:
#       - AvgPerceptronTests
#       - BackoffTaggerTests
#       - NLP.Chunk.AvgPerceptronChunkerTests
#       - NLP.Chunk.AvgPerceptronChunkerTests
#       - NLP.Corpora.BrownTests
#       - NLP.Corpora.ConllTests
#       - NLP.Similarity.VectorSimTests
#       - NLP.POSTests
#       - NLP.POS.LiteralTaggerTests
#       - NLP.POS.UnambiguousTaggerTests
#       - NLP.Extraction.ParsecTests
#       - NLP.TypesTests
#       - NLP.Types.IOBTests
#       - NLP.Types.TreeTests
#       - Data.DefaultMapTests
#       - Corpora
#       - TestUtils
#       - IntegrationTests

#     dependencies:
#       - HUnit
