flags: {}
packages:
- '.'
extra-deps:
- cereal-text-0.1.0.2
- fullstop-0.1.4
- tokenize-0.3.0
- git: https://github.com/bingis-khan/mboxf.git
  commit: a6352c07388493a08fbd1c07c3b41962ee811624
resolver: lts-21.3
